[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn server:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --preload"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[[services]]
memory = 2048
